config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "businesses#index"
  # get 'ui(/:action)', controller: 'ui'
  resources :businesses, only: [:index, :show, :new, :create] do
    resources :reviews, only: [:new, :create]
  end
  get 'register', to: 'users#new'
  get 'login', to: "sessions#new"
  get 'logout', to: "sessions#destroy"
  resources :sessions, only: [:create]
  resources :users, only: [:create, :show]
  resources :reviews, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/business.rb
class Business < ActiveRecord::Base
  has_many :reviews, -> { order('created_at DESC') }
  has_many :business_categories
  has_many :categories, through: :business_categories
  validates_presence_of :name, :description, :phone_number, :address_first_line, :city, :post_code, :expense
  validates_numericality_of :expense, greater_than: 0, less_than: 5, only_integer: true

  def rating
    return 0 unless reviews.any?
    avg =  reviews.map(&:rating).reduce(&:+) / reviews.count.to_f
    to_nearest_half(avg)
  end

  private

  def to_nearest_half(num)
    ( num * 2 ).round / 2.0
  end
end

app/models/business_category.rb
class BusinessCategory < ActiveRecord::Base
  belongs_to :business
  belongs_to :category
  validates_uniqueness_of :business_id, scope: :category_id
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :business_categories
  has_many :businesses, through: :business_categories
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :business
  belongs_to :user
  validates_presence_of :rating, :body
  validates_numericality_of :rating, less_than: 6, greater_than: 0, only_integer: true
  validates_uniqueness_of :business_id, scope: :user_id, message: "You have already submitted a review for this business"
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :reviews, -> { order('created_at DESC') }
  has_secure_password
  validates_presence_of :first_name, :last_name, :email, :post_code, :city
  validates_uniqueness_of :email, case_sensitive: false
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates_format_of :email, with: VALID_EMAIL_REGEX
  before_save { self.email = self.email.downcase if self.email }

  def profile_picture
    avatar.blank? ? "avatar.png" : avatar
  end

  def thumbnail
    thumb.blank? ? profile_picture : thumb
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def can_write_review?(business)
    !reviews.map(&:business_id).include?(business.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def require_user
    unless logged_in?
      flash[:danger] = "You must be logged in for that."
      redirect_to login_path
    end
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end
end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  before_action :require_user, only: [ :new, :create ]
  def index
    @businesses = Business.order('created_at DESC').paginate(page: params[:page], per_page: 10)
  end

  def show
    @business = Business.find(params[:id])
  end

  def new
    @business = Business.new
  end

  def create
    @business = Business.new(business_params)
    if @business.save
      flash[:success] = "Business Created"
      redirect_to businesses_path
    else
      render :new
    end
  end

  private

  def business_params
    params.require(:business).permit(:name, :description, :address_first_line, :city, :post_code, :phone_number, :expense, :category_ids => [])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :require_user, only: [ :new, :create ]
  def index
    @reviews = Review.order('created_at DESC').paginate(page: params[:page], per_page: 25)
  end

  def new
    @business = Business.find(params[:business_id])
    @review = Review.new
  end

  def create
    @business = Business.find(params[:business_id])
    unless current_user.can_write_review?(@business)
      flash[:error] = "You have already submitted a review for this business"
      redirect_to @business
    else
      create_the_review
    end
  end

  private

  def create_the_review
    @review = @business.reviews.build(review_params)
    @review.user = current_user
    if @review.save
      flash[:success] = "Successfully added the review"
      redirect_to @business
    else
      flash.now[:danger] = "An error occured"
      render :new
    end
  end
  
  def review_params
    params.require(:review).permit(:rating, :body)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :require_user, only: [ :destroy ]

  def new
    redirect_to root_path if logged_in?
  end

  def create
    user = User.find_by_email(params[:email].downcase)
    if user && user.authenticate(params[:password])
      create_session(user)
    else
      flash.now[:danger] = "Error - Incorrect Credentials"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:info] = "Successfully signed out."
    redirect_to root_path
  end

  private

  def create_session(user)
    session[:user_id] = user.id
    flash[:success] = "Welcome #{user.first_name}!"
    redirect_to user_path(user)
  end
end

app/controllers/ui_controller.rb
class UiController < ApplicationController
  before_action do
    redirect_to root_path if Rails.env.production?
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user, only: [ :show ]
  def new
    redirect_to root_path if logged_in?
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Your account was successfully created"
      redirect_to login_path
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :city, :post_code, :avatar, :thumb)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/businesses/_business.html.haml
%li
  %div.business-body
    %div.business-left
      = link_to(business) do
        %h3= business.name
      %div.business-review-summary
        %div{ class: "stars stars-show stars-show-#{ (business.rating * 10).round }" }
        %span #{pluralize(business.reviews.count, "Review")}
        %p
          - business.expense.times do
            $
          \-
          - business.categories.each do |category|
            %span= category.name.titleize
    %div.business-right
      - if logged_in? && current_user.can_write_review?(business)
        = link_to new_business_review_path(business), class: 'review_button' do
          = fa_icon 'star'
          %span Write A Review
      %div.business-address
        %p.address.line-1= business.address_first_line
        %p.address.city= "#{business.city}, #{business.post_code}"
        %p.address.phone= business.phone_number
  %div.description
    %p= business.description

app/views/businesses/_form.html.haml
= render "shared/errors", obj: business

%div#new_business
  %div.login-right
  %div.login-left
    = form_for @business, html: { id: "add_new_business" } do |f|
      %h3 New Business
      %p
        Add a new Business
      %fieldset
        = f.label :name, "Business Name"
        = f.text_field :name, placeholder: "Business Name"
        = f.label :description
        = f.text_area :description, size: "34x4", placeholder: "An example description"
        = f.label :address_first_line, "Address - First Line"
        = f.text_field :address_first_line, placeholder: "e.g. 123 Downing Street"
        = f.label :city
        = f.text_field :city, placeholder: "e.g. Brompton"
        = f.label :post_code, "Post Code"
        = f.text_field :post_code, placeholder: "e.g. XX2 00X"
        = f.label :phone_number, "Phone Number"
        = f.text_field :phone_number, placeholder: "e.g. 07777222111"
        = f.label :expense, "Expense Rating"
        = f.select :expense, (1..4).to_a.map { |n| [n.to_s, n] }.prepend([ "Select Expense Rating", nil ]), { selected: '', disabled: '' }
        = f.collection_select :category_ids, Category.all.to_a.prepend(Category.new(name: "Select Categories")), :id, :name, { disabled: ""}, { class: 'collection', multiple: true }
        = f.button f.object.new_record? ? "Create" : "Update"

app/views/businesses/index.html.haml
- content_for(:title, "Home")
- content_for(:page_heading) do
  %header.main
    %h3.content Top Businesses
%div.business-index
  %ul
    = render @businesses
%div
  = will_paginate @businesses, renderer: WillPaginate::ActionView::BootstrapLinkRenderer

app/views/businesses/new.html.haml
- content_for(:title, "New Business")
- content_for(:page_heading) do
  %header.main
    %h3 Add Business
= render "form", business: @business

app/views/businesses/show.html.haml
- content_for(:title, "Business Page")
- content_for(:page_heading) do
  %header.main_business
    %div.content
      %div.left
        %h4= @business.name
        %div.business-review-summary
          %div{ class: "stars stars-show-big stars-show-#{ (@business.rating * 10).round }" }
          %span= pluralize(@business.reviews.count, "Review")
          %p
            - @business.expense.times do
              $
            \-
            - @business.categories.each do |category|
              %span= category.name.titleize
      %div.right
        - if logged_in? && current_user.can_write_review?(@business)
          = link_to new_business_review_path(@business) do
            = fa_icon 'star'
            %span Write A Review
        %div.business-address
          %p.address.line-1= @business.address_first_line
          %p.address.city= "#{@business.city}, #{@business.post_code}"
          %p.address.phone= @business.phone_number
- if @business.reviews.any?
  %div.reviews-index
    %h3 Recent Reviews
    %ul.reviews-list
      - @business.reviews.each do |review|
        = render "reviews/review", show_business: false, review: review
      

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= "#{yield(:title)}| YelpVersion"
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  %body
    = render 'shared/header' 
    = render 'shared/messages'
    = yield(:page_heading)
    %main.content
      = yield
    = render "shared/footer"

app/views/reviews/_review.html.haml
- show_business = show_business.nil? ? true : show_business
- show_user = show_user.nil? ? true : show_user
%li
  %div.reviews-body
    - if show_user
      %div.reviews-left
        = image_tag(review.user.thumbnail)
        = link_to(review.user) do
          %p= review.user.full_name
        %p= review.user.city
        = fa_icon "star"
        %span= pluralize(review.user.reviews.count, "Review")
    %div.reviews-right
      - if show_business
        %div.business-review-summary
          = link_to(review.business) do
            %h3= review.business.name
        %div.business-address
          %p.address= "#{review.business.address_first_line}, #{review.business.city}"
      %div{ class: "stars stars-show stars-show-#{review.rating * 10}" }
      %small= review.created_at.strftime("%d-%b-%y")
      %div.review
        %p= review.body

app/views/reviews/index.html.haml
- content_for(:title, "Recent Reviews")
- content_for(:page_heading) do
  %header.main
    %h3.content Recent Reviews
%div.reviews-index
  %ul.reviews-list
    = render @reviews
%div
  = will_paginate @reviews, renderer: WillPaginate::ActionView::BootstrapLinkRenderer
      

app/views/reviews/new.html.haml
- content_for(:title, "New Review")
- content_for(:page_heading) do
  %header.main
    %h3 Write A Review
%div.business_detail
  = link_to @business do
    %h4= @business.name
  %p
    - @business.expense.times do
      $
    \-
    - @business.categories.each do |category|
      %span= category.name.titleize

  %p= @business.address_first_line
  %p= "#{@business.city}, #{@business.post_code}"
  %p= "#{@business.phone_number}"

%h5#your-review Your Review:
= form_for [@business, @review] do |f|
  = render 'shared/errors', obj: @review
  %div.review-form(tabindex='-1')
    %div.review-box
      %section.set_rating
        %div.stars.stars-show-big.stars-show-0.set_stars
          - 5.times do |i|
            = f.radio_button :rating, (i + 1)
        %span Choose a rating
    %div.text-area
      = f.text_area :body, placeholder: 'Your review helps others learn about great local businesses'
  = f.button "Submit Review", id: "review_submit"

app/views/shared/_errors.html.haml
- if obj.errors.full_messages.any?
  %div.alert.alert-danger
    - obj.errors.full_messages.each do |msg|
      %p= msg

app/views/shared/_footer.html.haml
%footer
  %div.content
  %div#background-city
  %div#copyright Copyright &copy 2017 Andy-Ez

app/views/shared/_header.html.haml
%header
  %div.header
    %div.content
      =link_to 'Home', root_path, class: 'brand'
      %span#sign-up= link_to "Sign Up", register_path if !logged_in?
      %button.c-hamburger.c-hamburger--htx
        %span toggle menu
  %nav
    %div.content
      %ul.nav-list
        %li= link_to "Businesses", businesses_path
        %li= link_to "Add Business", new_business_path
        %li= link_to "Recent Reviews", reviews_path
        - if logged_in?
          %li= link_to "My Profile", user_path(current_user)
      %span#log-in= logged_in? ? link_to("Log Out", logout_path) : link_to( "Log In", login_path)

app/views/shared/_messages.html.haml
- if flash.any? 
  - flash.each do |class_name, msg|
    %div{ :class => "alert flash alert-#{class_name}" }
      %div.content= msg

app/views/ui/add_business.html.haml
- content_for(:title, "New Review")
- content_for(:page_heading) do
  %header.main
    %h3 Add Business
%div#new_business
  %div.login-right
  %div.login-left
    %form#add_new_business
      %h3 New Business
      %p
        Add a new Business
      %fieldset
        %input(type='text' name='name' placeholder='Business Name' )
        %input(type='text' name='address_line_1' placeholder='Address Line 1' )
        %input(type='text' name='city' id='city' placeholder='City')
        %input(type='text' name='post_code' placeholder='Postal Code')
        %input(type='text' name='phone_number' placeholder='Phone Number')
        %input(type='number' name='expense' placeholder='Expense Rating 1-4' min='1' max='4')
        %select(multiple)
          %option(disabled selected) Select Categories
          %option Category
          %option Another
          %option Third
      %button(type='submit') Create

app/views/ui/add_review.html.haml
- content_for(:title, "New Review")
- content_for(:page_heading) do
  %header.main
    %h3 Write a Review
%div.business_detail
  = link_to "#" do
    %h4 Newfoundland Burger Co.
  %p
    £££ - 
    %span Takeaway
    %span Fast Food
    %Span Burgers
  %p 102 Park Avenue Way
  %p London, XX2 00X
  %p 0207-777-7878

%h5#your-review Your Review:
%form(action='' method='post')
  %div.review-form(tabindex='-1')
    %div.review-box
      %section.set_rating
        %div.stars.stars-show-big.stars-show-0.set_stars
          - 5.times do |i|
            %input(type='radio' name='rating' id='rating-#{ i + 1 }' value='#{ i + 1 }')
        %span Choose a rating
    %div.text-area
      %textarea(placeholder='Your review helps others learn about great local businesses' name='review_body' id='review_body')
  %button(type='submit' id='review_submit')
    Submit Review

app/views/ui/businesses.html.haml
- content_for(:title, "Home")
- content_for(:page_heading) do
  %header.main
    %h3.content Top Businesses
%div.business-index
  %ul
    %li
      %div.business-body
        %div.business-left
          = link_to("#") do
            %h3 Business Title OF Carnegie Melon Melons and Pancakes
          %div.business-review-summary
            %div.stars.stars-show.stars-show-35
            %span 183 reviews
            %p
              £££ - 
              %span Takeaway
              %span Fast Food
              %Span Burgers
        %div.business-right
          %div.business-address
            %p.address.line-1 Address Line 1
            %p.address.city Swindon, PCODE
            %p.address.phone 0207-777-6452
      %div.description
        %p
          Lorem ipsum text lorem ipsum text lorem pisum text Lorem ipsum text lorem ipsum text lorem pisum text Lorem ipsum text lorem ipsum text lorem pisum text Lorem ipsum text lorem ipsum text lorem pisum text Lorem ipsum text lorem ipsum text lorem pisum text
      %li
        %div.business-body
          %div.business-left
            = link_to("#") do
              %h3 Another Business Here Selling Cars
            %div.business-review-summary
              %div.stars.stars-show.stars-show-0
              %span 0 reviews
              %p
                £ - 
                %span Audi
                %span Mercedes
                %Span Cars
          %div.business-right
            %div.business-address
              %p.address.line-1 Address Line 1
              %p.address.city Swindon, PCODE
              %p.address.phone 0207-777-6452
        %div.description
          %p
            Lorem ipsum text lopsum text lorem ipsum text lorem pisum text Lorem ipsum text lorem ipsum text lorem pisum text
      %li
        %div.business-body
          %div.business-left
            = link_to("#") do
              %h3 Third Business
            %div.business-review-summary
              %div.stars.stars-show.stars-show-50
              %span 1 reviews
              %p
                ££££ - 
                %span Kebabs
                %span Fast Food
                %Span Chicken
          %div.business-right
            %div.business-address
              %p.address.line-1 Address Line 1
              %p.address.city Swindon, PCODE
              %p.address.phone 0207-777-6452
        %div.description
          %p
            Lorem ipsum text lopsum text lorem ipsum text lorem pisum text Lorem ipsum text lorem ipsum text lorem pisum text

app/views/ui/index.html.haml
%section.ui-index
  %ul
    - Dir.glob('app/views/ui/*.html.haml').sort.each do |file|
      - wireframe = File.basename(file, '.html.haml')
      - unless wireframe == 'index' || wireframe.match(/^_/)
        %li= link_to wireframe.titleize, action: wireframe

app/views/ui/login.html.haml
- content_for(:title, "Login")
%div#login-page
  %div.login-right
  %div.login-left
    %form
      %h3 Log in to Yelp
      %p
        New to Yelp?
        =link_to "Sign Up", "#"
      %fieldset
        %input(type='email' placeholder='Email')
        %input(type='password' placeholder='Password')
      %button(type='submit') Log In
      %div
        %small
          New to Yelp?
          =link_to "Sign Up", "#"

app/views/ui/register.html.haml
- content_for(:title, "Register")
%div#login-page
  %div.login-right
  %div.login-left
    %form
      %h3 Sign Up for Yelp
      %p
        Connect with great local businesses
      %fieldset
        %input(type='text' name='first_name' placeholder='First Name' class='name')
        %input(type='text' name='last_name' placeholder='Last Name' class='name')
        %input(type='email' name='email' placeholder='Email')
        %input(type='text' name='city' placeholder='City')
        %input(type='text' name='post_code' placeholder='Postal Code')
        %input(type='password' name='password' placeholder='Password')
      %button(type='submit') Log In
      %div
        %small
          Already on Yelp?
          =link_to "Log In", "#"

app/views/ui/reviews.html.haml
- content_for(:title, "Recent Reviews")
- content_for(:page_heading) do
  %header.main
    %h3.content Recent Reviews
%div.reviews-index
  %ul.reviews-list
    %li
      %div.reviews-body
        %div.reviews-left
          = image_tag("avatar")
          = link_to("#") do
            %p Cathy Duran
          %p London
          = fa_icon "star"
          %span 10 Reviews
        %div.reviews-right
          %div.business-review-summary
            = link_to("#") do
              %h3 Business Cafe Name
          %div.business-address
            %p.address Address Line 1, London
          %div.stars.stars-show.stars-show-35
          %div.review
            %p
              Lorem ipsum text lorem ipsum text lorem pisum text Lorem ipsum text lorem ipsum text lorem pisum text Lorem ipsum text lorem ipsum text lorem pisum text Lorem ipsum text lorem ipsum text lorem pisum text Lorem ipsum text lorem ipsum text lorem pisum text
    %li
      %div.reviews-body
        %div.reviews-left
          = image_tag("avatar")
          = link_to("#") do
            %p Cathy Duran
          %p London
          = fa_icon "star"
          %span 10 Reviews
        %div.reviews-right
          %div.business-review-summary
            = link_to("#") do
              %h3 Business Cafe Name
          %div.business-address
            %p.address Address Line 1, London
          %div.stars.stars-show.stars-show-35
          %span 22/02/2017
          %div.review
            %p
              Lorem ipsum text lorem ipsum text lorem pisum text Lorem ipsum text lorem ipsum text lorem pisum text Lorem ipsum text lorem ipsum text lorem pisum text Lorem ipsum text lorem ipsum text lorem pisum text Lorem ipsum text lorem ipsum text lorem pisum text
      

app/views/ui/show_business.html.haml
- content_for(:title, "Business Page")
- content_for(:page_heading) do
  %header.main_business
    %div.content
      %div.left
        %h4 Business Title OF Carnegie Melon Melons and Pancakes
        %div.business-review-summary
          %div.stars.stars-show-big.stars-show-35
          %span 183 reviews
          %p
            £££ - 
            %span Takeaway
            %span Fast Food
            %Span Burgers
      %div.right
        = link_to "#" do
          = fa_icon 'star'
          %span Write A Review
        %div.business-address
          %p.address.line-1 Address Line 1
          %p.address.city Swindon, PCODE
          %p.address.phone 0207-777-6452
%div.reviews-index
  %h3 Recent Reviews
  %ul.reviews-list
    %li
      %div.reviews-body
        %div.reviews-left
          = image_tag("avatar")
          = link_to("#") do
            %p Cathy Duran
          %p London
          = fa_icon "star"
          %span 10 Reviews
        %div.reviews-right
          %div.stars.stars-show.stars-show-35
          %div.review
            %p
              Lorem ipsum text lorem ipsum text lorem pisum text Lorem ipsum text lorem ipsum text lorem pisum text Lorem ipsum text lorem ipsum text lorem pisum text Lorem ipsum text lorem ipsum text lorem pisum text Lorem ipsum text lorem ipsum text lorem pisum text
    %li
      %div.reviews-body
        %div.reviews-left
          = image_tag("avatar")
          = link_to("#") do
            %p Cathy Duran
          %p London
          = fa_icon "star"
          %span 10 Reviews
        %div.reviews-right
          %div.stars.stars-show.stars-show-35
          %span 22/02/2017
          %div.review
            %p
              Lorem ipsum text lorem ipsum text lorem pisum text Lorem ipsum text lorem ipsum text lorem pisum text Lorem ipsum text lorem ipsum text lorem pisum text Lorem ipsum text lorem ipsum text lorem pisum text Lorem ipsum text lorem ipsum text lorem pisum text
      

app/views/ui/show_user.html.haml
- content_for(:title, "User Profile")
- content_for(:page_heading) do
  %header.main_user_banner
    %div.content#user_banner
      =image_tag('avatar')
      %header
        %h1
          Donald Duckleys
        %p
          London
        %p
          = fa_icon "star"
          %span 91 Reviews
%div.reviews-index.user
  %h3 Recent Reviews
  %ul.reviews-list
    %li
      %div.reviews-body
        %div.reviews-right.user
          %div.business-review-summary
            = link_to("#") do
              %h3 Business Cafe Name
          %div.business-address
            %p.address Address Line 1, London
          %div.stars.stars-show.stars-show-35
          %div.review
            %p
              Lorem ipsum text lorem ipsum text lorem pisum text Lorem ipsum text lorem ipsum text lorem pisum text Lorem ipsum text lorem ipsum text lorem pisum text Lorem ipsum text lorem ipsum text lorem pisum text Lorem ipsum text lorem ipsum text lorem pisum text
    %li
      %div.reviews-body
        %div.reviews-right.user
          %div.business-review-summary
            = link_to("#") do
              %h3 Business Cafe Name
          %div.business-address
            %p.address Address Line 1, London
          %div.stars.stars-show.stars-show-35
          %span 22/02/2017
          %div.review
            %p
              Lorem ipsum text lorem ipsum text lorem pisum text Lorem ipsum text lorem ipsum text lorem pisum text Lorem ipsum text lorem ipsum text lorem pisum text Lorem ipsum text lorem ipsum text lorem pisum text Lorem ipsum text lorem ipsum text lorem pisum text
      
      

app/views/users/_form.html.haml
= render 'shared/errors', obj: user
= form_for user do |f|
  %h3 Sign Up for Yelp
  %p
    Connect with great local businesses
  %fieldset
    %div.form-grouping.name
      = f.label :first_name, "First Name"
      = f.text_field :first_name, placeholder: "e.g. John"
    %div.form-grouping.name
      = f.label :last_name, "Surname"
      = f.text_field :last_name, placeholder: "e.g. Alexander"
    = f.label :email
    = f.email_field :email, placeholder: "j.alex@example.com"
    = f.label :avatar, "Profile Image URL (optional)"
    = f.url_field :avatar, placeholder: "http://example.com"
    = f.label :city
    = f.text_field :city, placeholder: "e.g. Birmingham"
    = f.label :post_code, "Post Code"
    = f.text_field :post_code, placeholder: "e.g. BR1 XX0"
    = f.label :password
    = f.password_field :password
  = f.button :Register
  %div
    %small
      Already on Yelp?
      =link_to "Log In", login_path

app/views/users/new.html.haml
- content_for(:title, "Register")
%div#login-page
  %div.login-right
  %div.login-left
    = render "form", user: @user

app/views/users/show.html.haml
- content_for(:title, "User Profile")
- content_for(:page_heading) do
  %header.main_user_banner
    %div.content#user_banner
      = image_tag(@user.profile_picture)
      %header
        %h1
          = @user.full_name
        %p
          = @user.city
        %p
          = fa_icon "star"
          %span= pluralize(@user.reviews.count, "Review")
- if @user.reviews.any?
  %div.reviews-index.user
    %h3 Recent Reviews
    %ul.reviews-list
      - @user.reviews.each do |review|
        = render 'reviews/review', { review: review, show_user: false }
      